#!/usr/bin/env bash
set -e

SLP_VERSION=v2.6.7

# echo "Downloading skylark"
# wget -O skylark.tar.gz https://github.com/GreenNerd/skylark/archive/$SLP_VERSION.tar.gz
# echo "Download completed"

echo "Building the production image"
docker build -t skylark/production:$SLP_VERSION .
