#!/usr/bin/env bash
set -e

echo "Building the production image"
docker build -t registry.cn-hangzhou.aliyuncs.com/skylark/production:$VERSION .
docker push registry.cn-hangzhou.aliyuncs.com/skylark/production:$VERSION
