#!/usr/bin/env bash
set -e

cd /var/www/skylark

bundle config --local mirror.https://rubygems.org https://gems.ruby-china.org

bundle install --deployment --without test development -j4 && \
  find /var/www/skylark/vendor/bundle -name tmp -type d -exec rm -rf {} +

NODE_ENV=production yarn install

bundle clean
