#!/usr/bin/env bash
set -e

cd ./images/production/skylark
git fetch origin gxzh
git checkout origin/gxzh

head_sha=$(git rev-parse --short HEAD)
version=$(cat VERSION)
export VERSION="$version-$head_sha"

cd ..

./prepare/run
./build

ssh root@gxzh.cdht.gov.cn -tt -- "\
cd /var/skylark;\
echo 'SLP_VERSION=$VERSION' > .env;\
./scripts/update
"
