#!/usr/bin/env bash
set -e

cd ./images/production/skylark
git fetch origin tcyx-fork
git checkout origin/tcyx-fork

head_sha=$(git rev-parse --short HEAD)
version=$(cat VERSION)
export VERSION="$version-$head_sha"

cd ..

./prepare/run
./build

ssh skylark@110.185.102.13 -tt -- "\
cd /var/skylark;\
echo 'SLP_VERSION=$VERSION' > .env;\
./scripts/update
"
