#!/usr/bin/env bash
set -eux

touch app.local.env
touch elasticsearch.local.env
docker-compose build
docker-compose run app bundle exec rails db:create
docker-compose run app bundle exec rails db:schema:load
docker-compose run app bundle exec rails assets:precompile
